name: CI Pipeline

on: 
  push:
    branches:
      - main
      - testing
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Copy files from dish-it-react directory
        run: |
          mkdir -p build-directory
          cp -r dish-it-react/* build-directory/

      - name: Install dependencies for React App
        run: |
          cd build-directory
          npm install

      - name: Build React App for Production
        run: |
          cd build-directory
          npm run build

  testing:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Copy files from dish-it-react directory
        run: |
          mkdir -p testing-directory
          cp -r dish-it-react/* testing-directory/

      - name: Install dependencies
        run: |
          cd testing-directory
          npm install

      - name: Install Jest
        run: |
          cd testing-directory
          npm install jest
          npm install --save-dev jest-fetch-mock
          
      - name: Install Babel for parsing testing files
        run: |
          cd testing-directory
          npm install --save-dev @babel/preset-env @babel/preset-react babel-jest

      - name: Run tests
        run: |
          cd testing-directory
          npm test
