name: CI/CD Pipeline

on: 
  push:
    branches:
      - main
      - pipeline # for testing 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies for React APP
        run: |
          cd dish-it-react
          npm install

      - name: Run Unit Tests for React Application (with Jest)
        run: |
          cd dish-it-react
          npm test 
    
      - name: Build React App for Production
        run: |
          cd dish-it-react
          npm run build

  integration-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image for integration testing
        run: |
          docker build -f dish-it-react/Dockerfile.test -t integration-test .

      - name: Run Integration Tests
        run: |
          docker run --rm integration-test
  
  deploy:
    runs-on: ubuntu-latest
    needs: integration-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build React Docker Image
        run: |
          docker build -f dish-it-react/Dockerfile -t react-app .
      
      - name: Build Static Website Docker Image
        run: |
          docker build -f website/Dockerfile -t website-app .

      - name: Deploy with Docker Compose 
        run: |
          docker-compose -f docker-compose.yml up -d
